### PR TITLE
Behaves like

### LINKED ISSUE #12: Shared behaviours
I have a use case where I would like to use describe methods inside of a class in order to avoid test duplication by allowing me to use inheritance. Though, using classes is not strictly required. The end goal is to get to something like:

https://www.relishapp.com/rspec/rspec-core/docs/example-groups/shared-examples

proposed syntax without test class inheritance

```
@pytest_describe.shared
def share_a_measurable_object()

   def describe_include():
      def with_an_item_in_the_collection_returns_true(subject):
      def with_an_item_not_in_the_collection_returns_false(subject):

@pytest_describe.behaves_like('a measurable object')
def describe_my_special_array():

   @pytest.fixture
   def subject():
       return MySpecialArray()

@pytest_describe.behaves_like('a measurable object')
def describe_another_array():
   
   @pytest.fixture
   def subject():
         return AnotherArray()

   def it_does_something_special(subject):
```

### PR DESCRIPTION
**Pull request by ghostsquad**
resolves #12

### CODE REVIEW

**Comment by ropez** [comment]
Thank you very much for doing all the boring work. Documentation and everything!

I want merge this, but I'm not crazy about all the garbage you've added in .gitignore. Is that necessary?

**Comment by ghostsquad** [comment]
This is the default .gitignore that is used in github (with the small addition of pycharm). Nothing terribly special. You should run Tox locally and do a `git status`, and see all the files that are added. If you would still like this file removed, let me know, and I can rebase and change that.

**Comment by ropez** [comment]
Well, I tend to have git always ignore filetypes like `.pyc`, by adding them to my global .gitignore. There are no files generated by tox that I see with git status.

Of course, when cooperating with others I don't actually mind adding the relevant patters to the repo as well. But there were so much in that file that has nothing to do with this, like `.so`. Since I'm not using to tool that you used to generate that file, I'm stuck having to go through all of that if I'm going to change something in there :-/

**Comment by ghostsquad** [comment]
I've rebased to remove the `.gitignore` and to merge the commit that changes the version into my commit. 😄

**Comment by ropez** [comment]
Great work. I think this is a very nice feature. Thank you

**Pull request merged**
